theme: 
  - lawyerify-hugolify-theme
  - hugolify-theme

## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
build:
  writeStats: true
enableRobotsTXT: true
imaging:
  quality: 75
markup:
  tableOfContents:
    ordered: true
paginate: 24
removePathAccents: true

## STATIC
staticDir:
  - static1
  - static2