imports:
- path: github.com/hugolify/lawyerify-theme
- path: github.com/hugolify/lawyerify-netlify-cms
- path: github.com/hugolify/hugolify-theme-publications-concerned
- path: github.com/hugolify/hugolify-theme-publications
- path: github.com/hugolify/hugolify-theme-persons-statutes
- path: github.com/hugolify/hugolify-theme-persons
- path: github.com/hugolify/hugolify-theme
- path: github.com/hugolify/hugolify-netlify-cms
