_merge: deep
persons:
  _merge: deep
  thumbnail:
    _merge: deep
    desktop: "306x459"
    mobile: "138x216"
  large: 
    desktop: "330x495"
    mobile: "300x450"
  image:
    _merge: deep
    desktop: "416x624"
    mobile: "300x450"
