_merge: deep

# Javascript
animation: true
bootstrap:
  alert: false
  carousel: false
  collapse: false
  dropdown: false
  modal: false
  offcanvas: true
  popover: false
  scrollspy: false
  tab: false
  toast: false
  tooltip: false
carousel: false
map: true
parallax: 
  enable: false

# Image
image:
  retina:
    desktop: true
persons:
  _merge: deep
  thumbnail:
    _merge: deep
    desktop: '306x459'
    mobile: '138x216'
  large:
    desktop: '330x495'
    mobile: '300x450'
  image:
    _merge: deep
    desktop: '416x624'
    mobile: '360x540'
  publications_persons:
    _merge: deep
    desktop: '75x75'

# Admin
admin:
  cms: netlifycms