_merge: deep
persons:
  _merge: deep
  thumbnail:
    _merge: deep
    large: "330x495"
    desktop: "306x459"
    mobile: "153x230"
  image:
    _merge: deep
    desktop: "416x624"
    mobile: "330x495"
